.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-HUB\-TRAVIS" "1" "October 2013" "" ""
.
.SH "NAME"
\fBgit\-hub\-travis\fR \- Enable/Disable travis
.
.P
![yada][https://travis\-ci\.org/carloslima/git\-hub\-travis\.png?branch=master]
.
.SH "SYNOPSIS"
.
.nf

git hub travis\-enable [<repo>]  # Enables travis integration
git hub travis\-disable [<repo>] # Disables travis integration
.
.fi
.
.SH "DESCRIPTION"
This git\-hub plugin will let you enable/disable Travis continuous integration testing for any GitHub repository, from the command line\.
.
.SH "INSTALLATION"
Get the source code from GitHub:
.
.IP "" 4
.
.nf

git clone git@github\.com:carloslima/git\-hub\-travis
.
.fi
.
.IP "" 0
.
.P
Then run:
.
.IP "" 4
.
.nf

make test
make install        # Possibly with \'sudo\'
.
.fi
.
.IP "" 0
.
.SH "COMMANDS"
There are two git\-hub\-travis commands:
.
.TP
\fBgit hub travis\-enable [<owner>/<repository>]\fR:

.
.P
Turn travis on for a repository\.
.
.TP
\fBgit hub travis\-disable [<owner>/<repository>]\fR:

.
.P
Turn travis off for a repository\.
.
.SH "AUTHOR"
Written by Carlos Lima \fIcarlos@bpan\.org\fR
